{% set version = "1.1.0" %}
{% set sha256 = "83d70f1d3e87c72015f3c4f6a79a5e4d37f18eccc43984954c7f5e0e61f18a4f" %}

{% set build = 0 %}

package:
  name: libaatm
  version: {{ version }}

source:
  url: https://github.com/hpc4cmb/libaatm/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  skip: true  # [win]
  run_exports:
    - libaatm

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make
  host:
  run:

test:
  commands:
    - ls $PREFIX/lib  # [not win]
    - test -f $PREFIX/lib/libaatm${SHLIB_EXT}  # [not win]
    - dir %PREFIX%\\Library\\lib  # [win]
    - if not exist %PREFIX%\\Library\\lib\\aatm.dll exit 1  # [win]

about:
  home: https://github.com/hpc4cmb/libaatm
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Library of Alma Atmospheric Transmission at Microwaves Tools
  description: |
    This is a repackaged version of the ATM tools found at this upstream
    location:  https://bitbucket.sco.alma.cl/projects/ASW/repos/telcal/browse/TelCalResults/Libraries/ATM.
  dev_url: https://github.com/hpc4cmb/libaatm

extra:
  recipe-maintainers:
    - tskisner
